modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_issue_url}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_display_url}"
logoFile = "banner/banner.png"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "circleofcraft.mixins.json"

[[dependencies.circleofcraft]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.circleofcraft]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.circleofcraft]]
modId = "geckolib"
type = "required"
versionRange = "[4.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.circleofcraft]]
modId = "jei"
type = "optional"
versionRange = "[19.27,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.circleofcraft]]
modId = "jade"
type = "optional"
versionRange = "[15.10,)"
ordering = "AFTER"
side = "CLIENT"
